version: "3"
services:
  mysql:
    container_name: mysql
    image: mysql:5.6
    restart: always
    ports:
    - 3306:3306
    environment:
    - MYSQL_ROOT_PASSWORD=1287609286
    - MYSQL_DATABASE=pureftpd
    - MYSQL_USER=pureftpd
    - MYSQL_PASSWORD=1287609286
    volumes:
    - ./data:/var/lib/mysql
    - ./config:/etc/mysql

