version: "3"
services:
  portainer:
    container_name: portainer
    restart: always
    image: portainer/portainer-ce:2.11.1
    ports:
    - 9000:9000
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - portainer-data:/data
volumes:
  portainer-data:

